job: &job
  docker:
    - image: circleci/node:10-browsers
  working_directory: ~/repo

version: 2
jobs:
  test:
    <<: *job
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-v1-{{ .Branch }}
            - yarn-v1-master
            - yarn-v1-
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-v1-{{ .Branch }}-{{ checksum "shared/yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Lint
          command: yarn lint
      - persist_to_workspace:
          root: ~/repo
          paths: .

  publish:
    <<: *job
    steps:
      - attach_workspace:
          at: ~/repo
      - run: npm publish

release: &release
  filters:
    tags:
      only: /^v.*/
    branches:
      ignore: /.*/

any: &any
  filters:
    tags:
      only: /.*/

workflows:
  version: 2
  push:
    jobs:
      - test:
          <<: *any
      - publish:
          <<: *release
          requires:
            - test